server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

  # DB Setting
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

spring:
  jpa:
    hibernate:
      ddl-auto: update

api:
